**#In this notebook we are going to cover some of the most fundamentals concepts of tensord using tensorflow**

more specifically we are going to cover:

* Introduction to tensors
* getting information form tensors
* manipulating tensors
* tensors & numpy
* using @tf.function( a way to speed up your regular python functions)
*using gpu
*Excericses to try yourself


**##  Introduction to Tensors:**

In [ ]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__) #checking version of tf

2.15.0


In [ ]:
#creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check dimensions of the tensor
scalar.ndim

0

In [ ]:
#creating the vector using tf.constant
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#checking dimension of the vector
vector.ndim

1

In [ ]:
#creating matrix using tf.constant
matrix= tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#checking dimension of the matrix
matrix.ndim

2

In [ ]:
#another_matrix
another_matrix=tf.constant([[1,4],
                            [4,8],
                            [7,3]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 4.],
       [4., 8.],
       [7., 3.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#creating tensor:
tensor=tf.constant([[[4,5,6],[1,2,3]],
                    [[5,2,8],[9,6,3]],
                    [[7,8,9],[3,5,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[4, 5, 6],
        [1, 2, 3]],

       [[5, 2, 8],
        [9, 6, 3]],

       [[7, 8, 9],
        [3, 5, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

#Tips:

* scalar: a single number
* vector: a number with direction (1 dimensional)
* matrix :a 2 dimensional array of numbers
* Tensor : a n dimentional array of number(where n can be any number , 0 dimensional tensor is a scalar,1 dimentional tensor is a vector )

### **Creating The Tensor Using Variable**


In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changable_tensor=tf.Variable([10,7])
unchangable_tesnor=tf.constant([55,11])
changable_tensor,unchangable_tesnor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([55, 11], dtype=int32)>)

In [ ]:
#lets try change one of the elements of changable tensor
changable_tensor[0]=44

TypeError: ignored

In [ ]:
#lets try using .assign():
changable_tensor[0].assign(77)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([77,  7], dtype=int32)>

In [ ]:
#lets try change one of the elements of unchangable tensor
unchangable_tensor[0]=66

In [ ]:
#lets try using .assign():
unchangable_tesnor[0].assign(66)
unchangable_tesnor

#**Note**:-
* the value of tensors created using constant is not changable
* the value of tensors created using variable is changable
* .assign(X) function is used to change The value of the tensor
* rarely we decide in practice wheather we will use tf.constant or tf.varibale .tensorflow does it for you.however inn doubt we create it as constant and change it later if needed

**Creating Random Tensors:**

* Random tesnors are the tensrs of abitrary size and contains random numbers.

In [ ]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
#are they equal?
random_1,random_2, random_1==random_2
#they are equal beacuse they are from same seed(7)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the Oreder Of the elements of the Tensors:

In [ ]:
#shuffle a tensor(valuable when you want to shuffle your data so the inherant order doesnt effect learning)
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,8]])
#shuffle non shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  8]], dtype=int32)>

In [ ]:
#shuffle non shuffled tensor
tf.random.set_seed(42)          #global_seed
tf.random.shuffle(not_shuffled,seed=42) #operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  8]], dtype=int32)>

⚓**Excercise read through tensorflow documentation on random seed genration https://www.tensorflow.org/api_docs/python/tf/random/set_seed and write 5 examples

*If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

*If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

*If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

*If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

#Other Ways to Create Tensor:

In [ ]:
#creating tensor of the all ones:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Creating tensor of the all zeros
tf.zeros(shape=(3,4),dtype='int32')

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

### Turn Numpy Array Into Tensors:


* the main difference between numpy array and tensors is that tensors can be run on GPU (much faster for numerical computing)

In [ ]:
#you can also turn numpy array into Tensors:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

#X = tf.constant(some_matrix) #capital for matrix ir tensor
#y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A =tf.constant(numpy_A,shape=(2,3,4))# elements in tensor should be same as elements in array shape may vari.
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

* shape (tensor.shape)
* rank  (tensor.ndim)
* Axis or Dimension (tensor[0]),(tensor[:,1])
* size  (tf.size(tensor)) total no of the items in the tensor

In [ ]:
#create a rank 4 tensor
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape ,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
##getting various output of our tensor
print("datatype of every elements:",rank_4_tensor.dtype)
print("Number of dimensions(rank) is :",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("elements along the 0 axis:",rank_4_tensor.shape[0])
print("elements along the last axis:",rank_4_tensor.shape[-1])
print("total number of elements in our tensors:",tf.size(rank_4_tensor))
print("total number of elements in our tensors:",tf.size(rank_4_tensor).numpy())

datatype of every elements: <dtype: 'float32'>
Number of dimensions(rank) is : 4
shape of tensor: (2, 3, 4, 5)
elements along the 0 axis: 2
elements along the last axis: 5
total number of elements in our tensors: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensors: 120


### Indexing tensors:


Tensors can be indexed just like pyhon lists
  

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension from each index except final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension from each index except  second last
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#create a tensor with rank 2(dimension 2):
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# get the last item of each row of ank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# add In extra dimension to our rank_2_tensor
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#alternative of tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) #expand 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manupulating tensors:(tensors operations)

"+" , "-" ," / "," *"


In [ ]:
tensor=tf.constant([[10,7],
                    [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#additon
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#substraction
tensor -5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [ ]:
#originals tensor is as it is
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#division
tensor /2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
#multipliction:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

operations using Tensorflow:
 *this are faster as runns on gpu

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.divide(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

### Matix multiplication:

* inner dimension should match
* output matrix has outer dimensions of input matrix

In [ ]:
#mtrix multiplication using tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#matrix multiplication using python "@" operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#lets creat two matrices with same shape(3,2)
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
y=tf.constant([[7,8],
              [9,10],
              [11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
x @ y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(x,y) #error because inner dimension are not matching (3,2)(3,2)

InvalidArgumentError: ignored

In [ ]:
#reshaping y:
tf.reshape(y,shape=[2,3])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
x.shape,tf.reshape(y,shape=[2,3]).shape #here inner dimensions are matched

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
x @ tf.reshape(y,shape=[2,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#try to change shape of x instead of y
tf.matmul(tf.reshape(x,[2,3]),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
#difference between transpose and reshape
x,tf.transpose(x),tf.reshape(x,shape=[2,3])

#transpose flips the axes
#shuffle the tensor the shape we provide

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

** The dot product**:

* dot product is refered same as matrixmultiplication
* "tf.matmul()"
"tf.tensordot()" ,"@"

In [ ]:
#matrix multiplication using tf.tensordot() , either x or y should be transposed
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#perform matrixmultiplication between  x and y(transposed)
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#perform matrixmultiplication between x and y(reshaped)
tf.matmul(x,tf.reshape(y,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

generally when we performing matrix multiplication of two tensors if one of the axes doesn't lineup ,ypu will transpose the matrix rather than reshaping.

**Tensor Type Casting:**

In [ ]:
#create tensor with default dtype float32
B=tf.constant([10.1,7.3],dtype="float32")
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.1,  7.3], dtype=float32)>,
 tf.float32)

In [ ]:
#create tensor with dtype int32
C=tf.constant([66,85],dtype="int32")
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([66, 85], dtype=int32)>,
 tf.int32)

In [ ]:
#change from float32 to float16(reduce precision):
B=tf.cast(B,dtype=tf.float16)
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.1,  7.3], dtype=float16)>,
 tf.float16)

In [ ]:
B=tf.cast(B,dtype="float16")
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.1,  7.3], dtype=float16)>,
 tf.float16)

In [ ]:
C=tf.cast(C,dtype="float32")
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([66., 85.], dtype=float32)>,
 tf.float32)

**Aggregetting Tensors:**

In [ ]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

following are the Some other Aggregetting forms:

* mininum of the tensor
* maximum of the tensor
* mean of the tensor
* sum of the tensor

In [ ]:
#creating random tensor using numpy random
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37,  7, 30, 78, 43, 80, 21, 45,  6, 65, 70, 73,  7, 35, 84,  7, 44,
       97, 53, 96, 12, 70, 17, 46, 37, 32, 48, 27, 39, 84, 90, 66, 54, 83,
       12, 15, 55, 38, 51, 74, 65, 53, 32, 96, 36, 33, 49, 18, 59, 83])>

In [ ]:
tf.size(E),E.ndim,E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [ ]:
#find the maximum from the tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#get the mininmum of the tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
#Get the mean of the tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
#get the sum of the values of the tensors
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2452>

In [ ]:
#varience of the tensor
#tf.reduce_variance ---> not works

import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=689>

In [ ]:
#another way to find varience
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=689.83844>

In [ ]:
#deviation of the tensor:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.264776>

In [ ]:
tfp.stats.stddev(tf.cast(E,dtype="float32"))

<tf.Tensor: shape=(), dtype=float32, numpy=26.264776>

**find the positional maximum and minimum**

In [ ]:
#create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#finds the positional maximum index
tf.argmax(F)  # --> np.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#find the value of the positional maximum index
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#find max value of F
tf.reduce_max

<function tensorflow.python.ops.math_ops.reduce_max(input_tensor, axis=None, keepdims=False, name=None)>

In [ ]:
#find the positional minimum index from the tensor
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#find the value of the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**#Squeezing :**

removes shape 1 values rom the tensor

In [ ]:
#create a random tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
squeezed_G=tf.squeeze(G)
squeezed_G,squeezed_G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

#One_hot Encoding:

In [ ]:
#creating a list of indices (you need list of indices for one hot encoding)
some_list=[0,1,2,3] #could be red,green,purple,orange

#one_hot encoding our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for the one hot encoding
tf.one_hot(some_list,depth=4,on_value="saloni",off_value="nothing")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'saloni', b'nothing', b'nothing', b'nothing'],
       [b'nothing', b'saloni', b'nothing', b'nothing'],
       [b'nothing', b'nothing', b'saloni', b'nothing'],
       [b'nothing', b'nothing', b'nothing', b'saloni']], dtype=object)>

# Create Square,square_root,log

In [ ]:
#create a new tensor:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#squaring the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#square root(will error,requires not int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
#square root of a tensor
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#log of the tesnor
tf.math.log(H)

InvalidArgumentError: ignored

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensorflow & Numpy

tesnorflow interacts with numpy array


In [ ]:
#create  a tensor using nu,py
J=tf.constant(np.array([3.,7.,8.,77.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  7.,  8., 77.])>

In [ ]:
#convert our tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7.,  8., 77.]), numpy.ndarray)

In [ ]:
#convert our tensor to numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7.,  8., 77.]), numpy.ndarray)

In [ ]:
#The default types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,8.,77.]))
tensor_J=tf.constant([3.,7.,8.,77.])
#checking dtypes
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

#Finding gpu for the tensor

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
#go to the runtime, change runtime type to gpu

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Dec 27 00:26:53 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

*** Note ***: if we have cuda enabled gpu tensorflow automatically use it whenever possible